### ISSUE TITLE
Parent ui canvas start blinking when canvas plane distance set to the same as uicamera 's far clipping plane

### ISSUE THREAD

**Issue by Cm57** [mob-sakai/ParticleEffectForUGUI#103]
**Describe the bug**
Parent ui canvas start blinking when canvas plane distance set to the same as uicamera 's far clipping plane
**To Reproduce**
1. set camera projection to Orthographic
2. new a canvas set render mode to ScreenSpace-Camera,Plane Distance to the same as camera 's far clipping plane
3. Add UI Particle under canvas，Add other ui (ex. empty image)

**Expected behavior**
parent canvas won't blinking

**Screenshots**
![issue](https://user-images.githubusercontent.com/46776642/94528749-67227600-026b-11eb-8196-d68b22f04bc3.gif)

**Environment (please complete the following information):**
 - Version 2.3.0 3.0.0preview35,36
 - Platform: Editor(Windows)
 - Unity version: 2019.4.0f1
 - Build options: .Net 4.x

**Comment by 0xF6** [comment]
Set shader `UI/UIAdditive` at particle material

**Comment by Cm57** [comment]
> Set shader `UI/UIAdditive` at particle material

I try, but the same
![issue2](https://user-images.githubusercontent.com/46776642/94640486-7e1ba380-0311-11eb-8f48-2a2bc620aa1e.gif)

**Comment by mob-sakai** [comment]
@Cm57 
The issue is reproduced in my environment.
But it doesn't seem to be caused by UIParticle.

For example, adding an image that move on the z-axis in Animation causes the same problem.

![Oct-01-2020 16-09-26](https://user-images.githubusercontent.com/12690315/94778788-d5e50800-0400-11eb-8cd1-ac6aaadfa385.gif)
