### ISSUE TITLE
Fog is applied to the UI Particles

### ISSUE THREAD

**Issue by VergilUa** [mob-sakai/ParticleEffectForUGUI#155]
When using default fog + e.g. Mobile Particles Alpha Blended shader - fog is applied to UI particles, causing them to be single color.

**To Reproduce**
1. Toggle on fog in lighting settings;
2. Attach UI Particle + Particle System Prefab to UI
3. Run the scene

**Expected behavior**
No fog should be applied, or there should be an option to ignore it.

**Screenshots**
This is without fog enabled:
![image](https://user-images.githubusercontent.com/24496266/113254926-e141bf00-92cf-11eb-9edc-5f379c4c0eaa.png)
And this is with fog enabled:
![image](https://user-images.githubusercontent.com/24496266/113254957-eb63bd80-92cf-11eb-81a1-0fa5746636aa.png)

**Environment:**
 - Version 3.3.5
 - Platform: Editor (Windows), iOS
 - Unity version: 2020.1.8f1
 - Build options: IL2CPP, .Net 4.x, Built-in render pipeline.

**Comment by VergilUa** [comment]
Just FYI, modifying shaders to disable fog, e.g. like so:
`Fog { Mode Off }`
Works, but this requires shader modification ofc. If there's another solution, that would great.

**Comment by mob-sakai** [comment]
@VergilUa 
Sorry for my late reply.
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Unfortunately, we cannot disable fog in a material or in CanvasRenderer...

- Solution 1: Create a shader with `Fog { Mode Off }`
- Solution 2: Set the Canvas Render Mode to `Screen Space - Overlay`

**Comment by wappenull** [comment]
### Addendum to this issue
The issue will be worse and very confusing when using dark fog and linear fog.
Note that material in picture has shader **Mobile/Particles/Additive**

**Normal display without fog**
![image](https://user-images.githubusercontent.com/58169531/143395634-ddb6aa92-16e6-4d60-84c2-ed515457767c.png)

**Exponential Fog White** (This is OP's issue case)
![image](https://user-images.githubusercontent.com/58169531/143395745-ca8a5aca-97c2-480a-a4d0-398a1321ab1b.png)

**Exponential Fog Black**
The particle is now can barely be seen
![image](https://user-images.githubusercontent.com/58169531/143395782-bf469766-f81c-4fce-b434-14f9a683c604.png)

**Linear Fog Black**
Yes DAFUQ, It's completely **DISAPPEARED**! , this is the worst. I spent my time banging my head for hours.
![image](https://user-images.githubusercontent.com/58169531/143395850-5058db2f-7f7c-4ab7-acaf-5b34da462f92.png)

My game definitely has to use Fog because of dark and 3D game.
For future readers, here is my solution for now:
- Change that particle material you are using to non-mobile shader.
- Or to UI-Additive shader (That is bundled with ParticleEffectForUGUI)
- Or else, anything that mob-sakai suggested above.

### IDEA: 
@mob-sakai
As for usability/enhancement, for future users, To prevent this mistake,
could you detect this scenario and show warning in UIParticle inspector?

Maybe something like:
```cs
// UIParticleEditor.cs:179
foreach( var m in mats )
{
    if( RenderSettings.fog && m.shader.name.Contains( "Mobile/" ) )
    {
        EditorGUILayout.HelpBox( "You are using mobile shader and Fog is on, rendering might be problem.", MessageType.Warning );
        break; // Only show once
    }
}
```

I have tried it and this is basic "fool-proof" detection.
![image](https://user-images.githubusercontent.com/58169531/143397938-7b44c90d-a569-40af-941b-e1660b648640.png)
