### ISSUE TITLE
Sub-effects under particle effects cannot change their offset positions?

### ISSUE THREAD

**Issue by zhanglongfei** [mob-sakai/ParticleEffectForUGUI#172]
![image](https://user-images.githubusercontent.com/10047133/131602628-62abcdea-79aa-48d7-bf37-de7611f34705.png)

Sub-effects under particle effects cannot change their offset positions

![GIF 2021-9-1 10-45-31](https://user-images.githubusercontent.com/10047133/131603555-53564bc2-6cad-47cf-a991-2ddd63837b78.gif)

Drag child effects in view location incorrect

![GIF 2021-9-1 10-39-24](https://user-images.githubusercontent.com/10047133/131603177-0f476c13-8d9e-4302-8a90-b59423717f35.gif)

The correct result  ↑

**Comment by mob-sakai** [comment]
@zhanglongfei 
Thank you for your reporting!
I would like to know more about this issue.
Could you please attach **a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories)** that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by zhanglongfei** [comment]
![GIF 2021-9-1 13-14-13](https://user-images.githubusercontent.com/10047133/131615828-8f682f65-d4ea-4ae5-a689-fb5cc6ca645c.gif)

I need to control the location of the sub effects under UIParticle, so I don't know if that's a problem？

[ParticleSystemDrag.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/7088428/ParticleSystemDrag.zip)

**Comment by zhanglongfei** [comment]
![image](https://user-images.githubusercontent.com/10047133/131621652-25ec2220-9b46-4f14-9d70-282e96344d06.png)

400x800 OK      1920x1080 No

**Comment by zhanglongfei** [comment]
これはバグですか?

**Comment by mob-sakai** [comment]
This is **not** an intentional design but a fundamental fix will not be easy.
I think that the impact is so great, so it should be fixed **in the next major version.**

I propose two solutions.

### Solution 1: Disable `UIParticle.ignoreCanvasScaler` and set `UIParticle.scale` to 1

These options provide easier scaling, but they do not work well in your case.

![image](https://user-images.githubusercontent.com/12690315/131932033-34bbf55d-236f-47b3-a6b9-2b68b725a73e.png)


### Solution 2: Attach a `UIParticle` component to the sub ParticleSystem

Separate the rendering into two `UIParticle` components.

**Comment by zhanglongfei** [comment]
Thank you for your response and look forward to the new release, the next major release estimated when to release
