### ISSUE TITLE
Error when using particle noise: Mesh '[UIParticleRenderer] Combine Instance Mesh': abnormal mesh bounds'

### ISSUE THREAD

**Issue by CollinPatrick** [mob-sakai/ParticleEffectForUGUI#213]
**Describe the bug**
I noticed that I get two errors whenever I exit play mode. I found that they do not occur when I disable the noise module on my particle system. It seems like there is a memory leak given Unity was using 18 gigs of my system's memory before crashing.

> Assertion failed on expression: 'ps->array_size()'
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleRenderer:UpdateMesh (UnityEngine.Camera) (at Assets/Scripts/Utilities/Plugins/UI Particles/Scripts/UIParticleRenderer.cs:240)
Coffee.UIExtensions.UIParticle:UpdateRenderers () (at Assets/Scripts/Utilities/Plugins/UI Particles/Scripts/UIParticle.cs:327)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at Assets/Scripts/Utilities/Plugins/UI Particles/Scripts/UIParticleUpdater.cs:82)
UnityEngine.Canvas:SendWillRenderCanvases ()

> Mesh '[UIParticleRenderer] Combine Instance Mesh': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(-338825116355735298246754845321370533888.00, -338821871170198713979487013761164771328.00, -338825927652119444313571803211421974528.00), max=(81129638414606681695789005144064.00, 223106505640168374663419764146176.00, 81129638414606681695789005144064.00). Please make sure the mesh is exported without any errors.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleRenderer:UpdateMesh (UnityEngine.Camera) (at Assets/Scripts/Utilities/Plugins/UI Particles/Scripts/UIParticleRenderer.cs:240)
Coffee.UIExtensions.UIParticle:UpdateRenderers () (at Assets/Scripts/Utilities/Plugins/UI Particles/Scripts/UIParticle.cs:327)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at Assets/Scripts/Utilities/Plugins/UI Particles/Scripts/UIParticleUpdater.cs:82)
UnityEngine.Canvas:SendWillRenderCanvases ()

**To Reproduce**
1, Enable noise on a particle system.
2. Press play in the editor.
3. Exit play mode.
4. See error.

**Expected behavior**
No errors in the console upon exiting play mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/40306723/176335890-3fe19ebe-b44d-4901-a2e5-51d87d7a5232.png)
![image](https://user-images.githubusercontent.com/40306723/176335926-27a266d6-1e37-4d62-8edd-676619c49474.png)

The small dots coming from the right are the particles.
![image](https://user-images.githubusercontent.com/40306723/176336007-c5ed2d56-f579-48f9-bf7a-db36b69fe99a.png)

**Environment:**
 - Version 4.1.3
 - Platform: Editor(Windows)
 - Unity version: 2022.1.1f1
 - Build options: IL2CPP, URP

**Additional context**
The particle system in question is nested inside a prefab.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
The issue is not reproduced on my environment...
I would like to know more about this issue.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.

**Comment by lfarkas73** [comment]
Hello, 
I have recognized this problem with the latest version.

Version 4.2.2
Platform: Editor(Windows)
Unity version: 2022.3.7f1
Build options: IL2CPP, BUILTIN

Easy to recreate, opened new empty default 3D project, added latest GIT package, imported UIParticle_Demo.
Many thanks for your fantastic asset.
Lajos

Assertion failed on expression: 'ps->array_size()'
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleRenderer:UpdateMesh (UnityEngine.Camera) (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleRenderer.cs:330)
Coffee.UIExtensions.UIParticle:UpdateRenderers () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticle.cs:503)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleUpdater.cs:80)
UnityEngine.UI.ScrollRect:LateUpdate ()

Mesh '[UIParticleRenderer] Combine Instance Mesh': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(0.00, 0.00, 0.00), max=(16001069492125579151405399003889664.00, 79316175099297370989568178471829504.00, 308585124126850166435263369183232.00). Please make sure the mesh is exported without any errors.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleRenderer:UpdateMesh (UnityEngine.Camera) (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleRenderer.cs:330)
Coffee.UIExtensions.UIParticle:UpdateRenderers () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticle.cs:503)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleUpdater.cs:80)
UnityEngine.UI.ScrollRect:LateUpdate ()

**Comment by wmltogether** [comment]
Hello there, I found this error with the latest version after upgrade to 2022.3.18f1

To Reproduce:
1, Enable Shape Module -> Set Shape to Rectangle or Box (Edge), -> Set Shape scale to (1,1,0) on a particle system.
2. Enter play mode.
3. See error logs.

To Fix:
Reset Shape z-scale to 1.

Reproduced with:
Unity 2022.3.11f1 - 2022.3.18f1
Not Reproduced with:
Unity 2021.3.x

Screenshots:
<img width="722" alt="Snipaste_2024-01-23_17-43-56" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/10459551/262abbb5-d2b8-4a44-b9c7-ca166551ed46">
<img width="465" alt="Snipaste_2024-01-23_17-43-45" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/10459551/12cc9a80-b3d9-48c3-b74d-88beb4980810">

**Comment by mob-sakai** [comment]
@wmltogether 
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by wmltogether** [comment]
@mob-sakai 
[MeshCombineError.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/14031504/MeshCombineError.zip)

Environment:
Unity 2022.3.18f1 Windows 11 x64
Universal Render Pipeline

To Reproduce:
Open `Scenes/MainScene.unity`, See Errors

Note:
Adding a particle prefab under the UIParticle results in the following AABB error.
New created particle without prefab is fine.

Error disappears when setting particle shape z-scale to 1 or unprefab the prefab instance.

**Comment by mob-sakai** [comment]
@wmltogether
Thank you!
The issue is reproduced on my environment.

**Comment by mob-sakai** [comment]
I tested several cases and found that errors can occur even when x-scale or y-scale is 0, depending on the type of shape.
When the shape module is enabled, I think we should skip processing if the scale is `x*y*z=0`.
