### ISSUE TITLE
Android: Particles works in editor player but does not shows in the build

### ISSUE THREAD

**Issue by Watcher3056** [mob-sakai/ParticleEffectForUGUI#233]
**Describe the bug**
Particles renders in editor player but not in Android Build(just nothing). I encountered this problem a long time before and this is a reason why I still did not used this package: particles just does not shows in Android build.
Canvas: Screen Space - Overlay

**To Reproduce**
1. Go to Unity3d
2. Select several particles from EpicToon FX asset
3. Make Android build
4. Launch on mobile
5. Result: no particles shown

**Expected behavior**
Particles shows same as in editor player
**Environment (please complete the following information):**
 - Version 4.1.7
 - Platform: Android
 - Unity version: 2021.3.11f1
 - Build options: IL2CPP, .Net 4.x, URP

**Additional context**
EpicToon FX, which uses LegacyShaders/Particles alot
I replaced LegacyShaders/Particles/Additive to UI/Additive and LegacyShaders/Particles/AlphaBlended with UI/Default as in Readme.md but it does not helped at all.

My previous thread here:
https://github.com/mob-sakai/ParticleEffectForUGUI/issues/80

**Comment by sunwangshu** [comment]
I came across similar issue on some of the iOS devices while using URP. 

**Describe the bug**
Particles renders in editor and some of the iOS devices, but not some other iOS devices. 
Canvas: Screen Space - Overlay
Shader channels - Everything

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Unity3d
2. Select several particles from EpicToon FX asset
3. Make iOS build
4. Launch on mobile
5. Result: no particles shown

**Expected behavior**
Particles shows same as in editor player

**Environment (please complete the following information):**
Version 3.3.9 & 4.1.7 
Platform: iOS
Unity version: 2021.3.4f1
Build options: IL2CPP, .Net Standard 2.1, URP

**Additional context**
* Some iOS device cannot see UI Particle and some device can. 
    * Can't see UI Particle: iPhone 12 Pro with iOS 15.6.1, and another older iPad (forgot the specs)
    * Can see UI Particle: My other iPad Pro 11inch (MTXR2LL/A) with iOS 14.7.1; another iPhone with iOS 16
* The particle on UI was using Sprites/Default & Mobile/Particles/Alpha Blended and can't show with UI Particle.
Interestingly, the other particle that use shader Sprites/Default without using UI Particle was working fine on the device that has issue.

**Comment by sunwangshu** [comment]
@Watcher3056 @mob-sakai 
My colleague suggested switching to `UI/Default`shader, it did solve the issue on my device. 
Actually it's only until later I saw the note in the documentation:
<img width="774" alt="Screen Shot 2022-11-23 at 4 22 58 PM" src="https://user-images.githubusercontent.com/14167797/203668145-4dd57fbb-2711-4d9d-8c3e-4d42c137ca27.png">

**Comment by mob-sakai** [comment]
Built-in shaders are no longer supported.
Use UI shaders instead.

In the next version, an error message will appear in the inspector when using the non-UI built-in shaders.
![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/6239f5ab-a661-4500-973f-51e3266d7dd7)
