### ISSUE TITLE
2 issues: 1) Scaling Particle System puts prewarmed particles in wrong location and 2) Sub-emitted particles in wrong location OnDeath

### ISSUE THREAD

**Issue by topher-mcbearslayer** [mob-sakai/ParticleEffectForUGUI#235]
**Describe the bug**
Hi mob-sakai! I've been sponsoring you for the last year or so and very appreciative of your library. Running the latest UI Particle, however, I have two issues and hoping you could take a look.

Two bugs:

1) When scaling a Particle System, it incorrectly places the pre-warmed particles in the wrong location. If you do NOT scale the Particle System, the prewarmed particles are correctly placed. This is an issue that was fixed in UI Particle 3.4 but has re-surfaced.

2) Fireworks Particle System sub-emitted explosion is being placed in incorrect location. Explosion is created OnDeath of parent particle. This used to work in UI Particle 3 but is not working in latest. Works in Editor, but not in Play Mode or on device.

**To Reproduce**
1. Download my attached sample project.
2. Use the buttons to create scaled and unscaled smoke particle emitters, notice the scaled particles prewarm in the incorrect location.
3. Observe that the fireworks particle sub-emitted particles (the explosion) are created in the incorrect location.

**Expected behavior**
Scaled and unscaled particles should place their prewarmed particles in the correct locations. Sub-emitted particles should be placed in correct position.

**Screenshots**
![image](https://user-images.githubusercontent.com/54777304/201385416-bdc75a2d-2d55-4223-9c2b-36c8cfe54ac6.png)
See attached sample project.

**Environment (please complete the following information):**
 - Version 4.1.7
 - Platform: Windows (Editor)
 - Unity version: 2021.3.12f1
 - Build options: N/A

**Additional context**
[ParticleTestv2.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/9991615/ParticleTestv2.zip)

**Comment by topher-mcbearslayer** [comment]
Are you still out there, @mob-sakai? :(

**Comment by mob-sakai** [comment]
Sorry for my late reply and thank you for your reporting!
I will test the project later.

**Comment by topher-mcbearslayer** [comment]
Any luck @mob-sakai ?

**Comment by PeterBacall** [comment]
Sorry this is not helpful, but found some other bugs relating to scaling. I don’t know if the UI Particle is supposed to work with “Screen Space - Overlay”, but it has some bugs on that mode. For example when scaling the UI (switching from 1080p to 4K), the Shapes of the Particle System remain their original size, they probably should’ve scaled with the UI etc. It also has the bugs with particles not getting emitted from the correct location (sometimes).

**Comment by topher-mcbearslayer** [comment]
Note for anyone having these issues. I reverted back to latest of version 3 ([3.3.12](https://github.com/mob-sakai/ParticleEffectForUGUI/releases/tag/3.3.12)) and no more issues. At some point in version 4 these issues started.

**Comment by Dongurea** [comment]
For Unity 2021.3.20f1, It occurs. I downgraded it for version 3.3.12 as topher-mcbearslayer said. And this issue disappears now.

**Comment by Dongurea** [comment]
I downgraded to version 3, but I had to restore to version 4 due to some features and effects design.
However, the errors in version 4 still persisted, so I modified some of the version 4 scripts to solve the problem.
I hope this will be helpful for users who have similar situations.


Here are the situations, configurations, and other conditions that I resolved:

## Bug situation and solution
 - ***(!) Caution: My solution may not be perfect! In particular, I have not tested whether the solution affects optimization. However, at least the issue of particles being incorrectly rendered has been resolved.***

### Bug Description:
The problem is that the position of the rendered particles is incorrectly set when the application is played.
 1. The particles are displayed correctly when ***Application.isPlaying*** is ***false***.
 2. When ***Application.isPlaying*** is ***true*** and the resolution is changed, the particle position is incorrectly rendered.
 3. The size of the rendered particles is normal.
 4. The problem is related to the ***Shape*** of the ***ParticleSystem***, and the initial position of the particles is incorrectly set.

### Environment:
 1. UI Particle version: 4.1.7
 2. Unity version: 2023.3.20f1
 3. Platform: Windows (Unity Editor), Android

### Solution:
 1. Open the 'UIParticleRenderer.cs' file.
 2. Comment out the following code in 'public void UpdateMesh(Camera bakeCamera)'.
```
#if UNITY_EDITOR
                if (!Application.isPlaying)
                {
                    SimulateForEditor(psPos - _prevPsPos, scale);
                }
                else
#endif
                {
                    ResolveResolutionChange(psPos, scale);
                    Simulate(scale, _parent.isPaused || _delay);

                    if (_delay && !_parent.isPaused)
                    {
                        Simulate(scale, _parent.isPaused);
                    }

                    // When the ParticleSystem simulation is complete, stop it.
                    if (!main.loop && main.duration <= _particleSystem.time && (_particleSystem.IsAlive() || _particleSystem.particleCount == 0))
                    {
                        _particleSystem.Stop(false);
                    }
                }
```

### Caution when using the solution:
 1. If the ***simulationSpace*** of the ***ParticleSystem*** is set to ***world***, it may not work properly.
 2. If the ***number of particles*** generated by the ***ParticleSystem*** is ***changed*** every time it is played, it may not work properly.
     - If the number of particles is changed every time it is played, the code related to ***_particleSystem.GetParticles()*** is necessary, so you should NOT comment out the entire code, but modify it to fit your own situation.

**Comment by Dongurea** [comment]
Also, the code that I asked to comment out contains several other features that I did not mention, so if there are any features in the commented-out code that are needed, they should be modified to fit one's own situation. In my case, I did not need any of those features, so I commented out the entire code.

**Comment by topher-mcbearslayer** [comment]
This is a great lead, thank you @Dongurea. I'll try to update back to v4 and comment out the same parts you did.

**Comment by JonathanVorich** [comment]
Same Issue! The solution of @Dongurea fixed my problem, but broke some particles in other places, so its not for any use for me. Will there be a fix soon @mob-sakai ??? Would be really really helpful.
