### ISSUE TITLE
IL2CPP Code Stripping Bug - "A scripted object (probably Coffee.UIExtensions.UIParticle?) has a different serialization layout when loading."

### ISSUE THREAD

**Issue by mattluard** [mob-sakai/ParticleEffectForUGUI#269]
Hi, writing this here in case it helps someone else, in IL2CPP builds I got this error at runtime:

```
A scripted object (probably Coffee.UIExtensions.UIParticle?) has a different serialization layout when loading. (Read 32 bytes but expected 140 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
```

(The note about `#ifdef UNITY_EDITOR` does not apply here, firstly because this works fine in Mono builds and not in IL2CPP builds, but secondly because I don't think there's any  `#ifdef`'s in the repo that match this description.)

This problem, I believe, is actually due to Unity's code-stripping, if you have ParticleEffectForUGUI as a package installed from the Package Manager, Unity's going to mess up during the build and strip too much from the package. It doesn't matter if you move the Package from `/Library/PackageCache/` to `/Packages/`, it still gets stripped.

From the [Unity docs on code stripping](https://docs.unity3d.com/Manual/ManagedCodeStripping.html):

```
Minimal - Unity searches only the UnityEngine and the .NET class libraries for unused code.
...
This is the default setting if you use the IL2CPP scripting backend.
```

The solution, such as it is right now, is to not use ParticleEffectForUGUI as a package at all, but rather copy it right into your `/Assets/` folder.

Nothing for @mob-sakai to do here, this is Unity's code stripping problem, except to perhaps add a note to the Installation section of the readme that says something like: "Due to Unity's code-stripping going too far, games targeting IL2CPP should not use the package installation but rather copy the repo into /Assets/, or else there will be serialization errors."

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
@mattluard 
Do you think adding the following code to UIParticle.cs would solve the problem?
```cs
[assembly:UnityEngine.Scripting.Preserve]
```

**Comment by ZhihaoJun** [comment]
Same problem here. Built standalone on windows platform with il2cpp backend. I got the error log when running:
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/5961602/4dbb89c5-4716-46f7-9264-d8c211d9ebe4)

My best guess is this macro that causes the bug since this is the only macro I found wrap a SerializeField of UIParticle.cs:
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/5961602/22e04d58-9781-4329-a86c-bb5c4379acab)

UIParticle version: 4.1.7
Unity version: 2021.3.28f1

**Comment by mob-sakai** [comment]
@ZhihaoJun 
umm...
It is not reproduced on my environment.

- 2021.3.28f1
- Windows IL2CPP
  - Managed Stripping Level: High
- UIParticle version: 4.1.7
  - Insatalled with UPM (https://github.com/mob-sakai/ParticleEffectForUGUI.git#4.1.7)
- Build scenes: UIParticle_Demo
  - Import from `UI Particle > Samples`

Could you please attach a minimal project (included Assets, Packages and ProjectSettings directories) that reproduces the issue?

**Comment by ZhihaoJun** [comment]
Sorry for the late reply, but I'm glad the bug has been fixed.

**Comment by ZhihaoJun** [comment]
Unfortunately, I encountered this issue again using the 4.4.0 version.
This time I was building Android version of my game.

However, I managed to solve it by putting entire UIParticle project in the `Assets` folder rather than in the `Packages` like mentioned above.

I think this issue is related to AssetBundle building process because my UI prefab is loading from an AssetBundle.
Everything is fine in the test project that is not using AssetBundle.

UIParticle version: 4.4.0
Unity version: 2021.3.28f1
IL2CPP backend

Optimization settings as below
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/5961602/9d6827f3-5b56-487a-b86c-9b771ece1972)

**Comment by tienassassin** [comment]
Hi sir @mob-sakai, looks like this issue hasn't been fixed yet.
UIParticle ver: 4.2.2
Unity ver: 2022.3.11f1
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/99780753/2f81a3f4-dccd-4cfb-8dc5-5a7eaf3e712d)

**Comment by tienassassin** [comment]
Hi sir @mob-sakai , looks like this issue hasn't been fixed yet.
UIParticle ver: 4.2.2
Unity ver: 2022.3.11f1
Please check. Thanks!
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/99780753/16152bbf-46c6-4548-ac58-9cf8d51180a3)

**Comment by mob-sakai** [comment]
@ZhihaoJun 
Thank you for your reporting!

@tienassassin 
As a workaround, try the way that @ZhihaoJun said.

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by tienassassin** [comment]
Hmm if I create an empty scene (same project as the one having the problem), then use UI Particle here, everything works fine... 😟

**Comment by mob-sakai** [comment]
- Has the project undergone a Unity version upgrade in the past?
- Are the assets assets that are loaded additionally, such as in AssetBundles? Also, were these assets built with an older version of Unity or UIParticle?
- If the assets are re-serialized, will the issue be resolved?
  `AssetDatabase.ForceReserializeAssets()`

I think that the root cause is the `different serialization layout`, meaning that the data structure differs between build time and load time.

**Comment by tienassassin** [comment]
Yeah, I upgraded Unity editor from 2022.3.7f1 to 2022.3.11f1
I just tried removing the UIParticle component, deleting the [generated] object then adding the UIParticle component again, everything works perfectly, it's a miracle
Thanks for your dedicated help, sir @mob-sakai

**Comment by mob-sakai** [comment]
If the same issue arises, please re-open this issue.
