### ISSUE TITLE
v4.7.2 Bug

### ISSUE THREAD

**Issue by mlzhp** [mob-sakai/ParticleEffectForUGUI#317]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.
![WX20240626-135423](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/74600440/b2405851-e118-4cca-8f32-7be70fb9f39e)
Particle layer is wrong, since v4.7.1, v4.7.0 Display is OK
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 4.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.3.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by mob-sakai** [comment]
Thank you for your reporting!
This is caused by a mismatch between min/max particle size and view size.
I will release an update as soon as possible that will make **"custome view size"** available.
![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/dd929959-1a37-420b-b13d-e849022b9c9d)

**Comment by mob-sakai** [comment]
Please try v4.8.0
