### ISSUE TITLE
With 'Screen Space - Camera' render mode, sorting is incorrect

### ISSUE THREAD

**Issue by young900101** [mob-sakai/ParticleEffectForUGUI#34]
<img width="1677" alt="ec83fc77-065b-4310-ab8c-2fcfe1ba5a7a" src="https://user-images.githubusercontent.com/38883838/51156688-a0f4f280-18b7-11e9-9eee-9932d3910de2.png">
<img width="1666" alt="b0e81049-1e34-48f6-89e0-ba0d3fb3f2a4" src="https://user-images.githubusercontent.com/38883838/51156693-a4887980-18b7-11e9-8a75-c13c50885dd1.png">

"xuanwo" is a particle.when i move down "xuanwo",it is above the GreenImage.Why?

**Comment by mob-sakai** [comment]
Hi @young900101 
Thank you for reporting.

I would like to know more information on this issue.
* Is it in play mode or in edit mode, or both?
* What Canvas.RenderMode did you set?
* Is ParticleSystem.Renderer disable?
* Please tell me the version of ParticleEffectForUGUI you are using. [e.g. v1.3.2]
* Can you submit a reproducible minimum project for this issue?

**Comment by young900101** [comment]
1.in play mode.in edit mode,the particle dosen't show.
2.Screen space-camera
3.disabled
4.1.3.2
5.wait a few minutes

**Comment by young900101** [comment]
[UIParticleTest.unitypackage.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2758336/UIParticleTest.unitypackage.zip)

**Comment by mob-sakai** [comment]
Thank you for your reply, @young900101 
Your unitypackage is working.

**Comment by mob-sakai** [comment]
Your unitypackage reproduced the issue.
![](https://user-images.githubusercontent.com/12690315/51172551-cf45f280-18f6-11e9-8208-291c021ec31b.gif)

Strangely, it works well with `Screen Space - Camera` render mode...🤔

**Comment by mob-sakai** [comment]
Oh, I'm sorry, I made a mistake. 
Actually, "with `Screen Space - Overlay`" is correct.

The scene works well with `Screen Space - Overlay` render mode.

**Comment by mob-sakai** [comment]
I do not know why, but it worked fine when setting `transform.localPosition.z` to `0.01`.
Why...?

**Comment by mob-sakai** [comment]
Try this script.
[UIParticle.cs](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2759633/UIParticle.cs.txt)

**Comment by young900101** [comment]
> Try this script.
> [UIParticle.cs](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2759633/UIParticle.cs.txt)

Aha~ A strange way!A strange result!
The sorting result is correct as long as z!= 0.But In my view,z is not affect the sorting result of the UGUI.So i feel confused.
Maybe this is not a perfect way to fix this bug,but it works fine.
Moreover,This is an awesome project.Thanks for your time!

**Comment by evakimox** [comment]
Hello there. Thanks for this great plugin. Sorry for bring this up 2 yrs after.

I am using this UGUIParticle tool with Version 3.3.0. I had no problem in Game view when my canvas is set to Screen Space - Overlay. I am still having sort issue with canvas set to Screen Space - Camera. 
I tested on 2 particle systems with Screen Space - Camera canvas. 
1. The first particle system I used the default created particle cone.
2. The second particle system has no z-axis speed, no z-axis behavior (all particles lies in the same plane)
I tried adjust z axis of the UIParticle. In this case, the 1st particle system always shows everything, while the 2nd particle system display depends on z-axis order.(It sorts element depend on z axis, but does not actually move the object)
![sortingProblemWithCameraCanvas](https://user-images.githubusercontent.com/11808878/117752340-2bac4900-b249-11eb-8dd0-d9ace63c37b4.png)

I realized the code has changed a lot since then, so I did not replace the UIParticles.cs file.
I am curious about how the plugin handles different particles.
