### ISSUE TITLE
Getting massive errors on editor

### ISSUE THREAD

**Issue by rozx** [mob-sakai/ParticleEffectForUGUI#67]
`TargetParameterCountException: Number of parameters specified does not match the expected number.`

`GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.
TargetParameterCountException: Number of parameters specified does not match the expected number.`

`The targets array should not be used inside OnSceneGUI or OnPreviewGUI. Use the single target property instead.`

`UnityEditor.EditorApplication:Internal_CallHierarchyHasChanged() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:334)
The serializedObject should not be used inside OnSceneGUI or OnPreviewGUI. Use the target property directly instead.`

`The targets array should not be used inside OnSceneGUI or OnPreviewGUI. Use the single target property instead.`

`The serializedObject should not be used inside OnSceneGUI or OnPreviewGUI. Use the target property directly instead.
UnityEditor.Editor:get_serializedObject()`

`The serializedObject should not be used inside OnSceneGUI or OnPreviewGUI. Use the target property directly instead.
UnityEditor.Editor:get_serializedObject()`

**The environment is Unity 2019.2.19f1 with UIParticle version 2.3.0**

I've also attached a sample project that can recreate the error, just open the prefab under **FX/EpicLootBoxEffects/Prefabs/Effects/4_Legendary/P_Stardust_02_Legendary.prefab**

[Test Project.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/4110562/Test.Project.zip)

Much appreciated.

**Comment by mob-sakai** [comment]
Hi @rozx ,

Thank you for your reporting!

**Comment by migus88** [comment]
We had the same issue when upgraded our project to Unity 2019 (from 2018). The fix is pretty simple. The Invoke method requires all parameters to be passed, even if there is an optional parameter in the method, you need to pass it on.
The 'Handles.DoSimpleEdgeHandle' method requires an additional bool parameter (optional with default value set to 'true') that is not passed from the UIParticleEditor.cs:602

In order to fix this issue, you need to change line 602 from this:

`float radius = Call<float> (typeof (Handles), "DoSimpleEdgeHandle", Quaternion.identity, Vector3.zero, shapeModule.radius);`

Into this:
`float radius = Call<float> (typeof (Handles), "DoSimpleEdgeHandle", Quaternion.identity, Vector3.zero, shapeModule.radius, true);`

**Comment by mob-sakai** [comment]
@migus88 
Thank you!

**Comment by mob-sakai** [comment]
Hmm, I think "use of reflection has some potential bugs".
I will use [OpenSesameCompiler (portable)](https://github.com/mob-sakai/OpenSesameCompilerForUnity) package to access to internals/privates, without reflection.
